INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('PS5', 'PS5', 'Consolas y Videojuegos', 'Consolas', 'PS5', 550, 'Consola PS5', 5, 2);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('NSW', 'NSW', 'Consolas y Videojuegos', 'Consolas', 'NSW', 350, 'Consola NSW', 5, 3);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('XBX', 'XBX', 'Consolas y Videojuegos', 'Consolas', 'XBX', 550, 'Consola XBX', 3, 1);
INSERT INTO IMAGEN (articulo_id, url) VALUES (1,'https://cdn.grupoelcorteingles.es/SGFM/dctm/MEDIA03/202311/16/00194481001017____4__640x640.jpg');
INSERT INTO IMAGEN (articulo_id, url) VALUES (2,'https://m.media-amazon.com/images/I/71eVf1+jn6L._AC_UF894,1000_QL80_.jpg');
INSERT INTO IMAGEN (articulo_id, url) VALUES (1,'https://media.direct.playstation.com/is/image/psdglobal/PS5-Slim-Hero-4');
INSERT INTO IMAGEN (articulo_id, url) VALUES (3,'https://assets.mmsrg.com/isr/166325/c1/-/ASSET_MMS_137562317?x=320&y=320&format=jpg&quality=80&sp=yes&strip=yes&trim&ex=320&ey=320&align=center&resizesource&unsharp=1.5x1+0.7+0.02&cox=0&coy=0&cdx=320&cdy=320');
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (1,'Primer Comentario PS5',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (1,'Segundo Comentario PS5',2);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (1,'Tercer Comentario PS5',4);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (2,'Primer Comentario NSW',4);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (2,'Segundo Comentario NSW',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (3,'Primer Comentario XBX',3);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (3,'Segundo Comentario XBX',4);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('PS5 Edicion digital', 'PS5 Edicion digital', 'Consolas y Videojuegos', 'Consolas', 'PS5', 450, 'Consola PS5', 3, 4);
INSERT INTO IMAGEN (articulo_id, url) VALUES (4,'https://media.game.es/COVERV2/3D_L/183/183225.png');
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (4,'Primer Comentario PS5 Edicion digital',5);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('Disgaea 5', 'D5NI', 'Consolas y Videojuegos', 'VIDEOJUEGOS', 'NSW', 50, 'Juego Disgaea 5 para NSW', 4, 3);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('Disgaea 5', 'D5NIPS', 'Consolas y Videojuegos', 'VIDEOJUEGOS', 'PS4', 50, 'Juego Disgaea 5 para PS4', 4, 3);
INSERT INTO IMAGEN (articulo_id, url) VALUES (5,'https://m.media-amazon.com/images/I/81zCLhvOULL._AC_UF894,1000_QL80_.jpg');
INSERT INTO IMAGEN (articulo_id, url) VALUES (6,'https://m.media-amazon.com/images/I/61g7Wbo-6NL._AC_UF894,1000_QL80_.jpg');
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (5,'Primer Comentario Disgaea 5 NSW',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (5,'Segundo Comentario Disgaea 5 NSW',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (6,'Primer Comentario Disgaea 5 PS4',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (6,'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod leo sed magna tincidunt, ac semper arcu ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed ac quam aliquam, ullamcorper ipsum quis, faucibus ipsum a, eget aliquet magna tincidunt. Mauris sed libero eget orci tincidunt condimentum, non ullamcorper sapien hendrerit. Donec ullamcorper metus euismod quam tincidunt, non tincidunt neque semper. Nunc sit amet quam id quam ullamcorper hendrerit, non euismod quam convallis. In hac habitasse platea dictumst. Vivamus et elit ac lacus viverra semper. Suspendisse potenti. Sed egestas, ante sed condimentum congue, ipsum metus mollis est, vitae semper quam quam et magna.',4);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('Disgaea 7', 'D7NIPS', 'Consolas y Videojuegos', 'VIDEOJUEGOS', 'PS5', 40, 'Juego Disgaea 7 para PS7', 4, 3);
INSERT INTO ARTICULO (nombre, codigo, seccion, categoria, subcategoria, precio, descripcion, stock, vendidos) VALUES ('Disgaea 7', 'D7NI', 'Consolas y Videojuegos', 'VIDEOJUEGOS', 'NSW', 40, 'Juego Disgaea 7 para NSW', 4, 3);
INSERT INTO IMAGEN (articulo_id, url) VALUES (7,'https://m.media-amazon.com/images/I/81dpM8X5bvL._AC_SL1500_.jpg');
INSERT INTO IMAGEN (articulo_id, url) VALUES (8,'https://m.media-amazon.com/images/I/81ci5hWmJXL._AC_SL1500_.jpg');
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (8,'Primer Comentario Disgaea 7 NSW',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (8,'Segundo Comentario Disgaea 7 NSW',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (7,'Primer Comentario Disgaea 7 PS5',5);
INSERT INTO VALORACION (articulo_id, comentario, estrellas) VALUES (7,'Segundo Comentario Disgaea 7 PS5',5);
INSERT INTO IMAGEN (articulo_id, url) VALUES (8,'https://m.media-amazon.com/images/I/71PJPNCQE3L._AC_SL1500_.jpg');
INSERT INTO IMAGEN (articulo_id, url) VALUES (8,'https://m.media-amazon.com/images/I/71FO8tlrVtL._AC_SL1500_.jpg');
INSERT INTO IMAGEN (articulo_id, url) VALUES (8,'https://m.media-amazon.com/images/I/71AMY8nNu-L._AC_SL1500_.jpg');
INSERT INTO USUARIO (username, password, email, enabled) VALUES ('usuario','usuario','usuario@usario.com',1);